run:
  timeout: 2m

skip-dirs:
  - .go-skynet

linters-settings:
  cyclop:
    max-complexity: 16
  gosec:
    excludes:
      - G114

lll:
  line-length: 120
  tab-width: 1

linters:
  enable:
    - bodyclose
    - cyclop
    - gochecknoglobals
    - goimports
    - gosec
    - lll
    - nilerr
    - noctx
    - sqlclosecheck
