environment: local
debug: true
web_app_url: "http://localhost:3000"
web_app_redirect_url: "/"
web_app_error_redirect_path: "/auth/unhandled"
registry:
  dns_address: localhost
  version: master
  fqdn: localhost
  jwt_signing_secret: super-secret
  host: 0.0.0.0
  port: 5000
  tls:
    enabled: false
    priv_key: .certs/registry.local
    pub_key: .certs/registry.local.crt
    services:
      - github
      - token
      - skynet_homescreen
oauth:
  github:
    client_id: dummy-gh-client-id
    client_secret: dummy-gh-client-secret
dfs:
  filebase:
    enabled: true
    type: "uplink"
    access_key: <access-key>
    secret_key: <access-secret-key>
    access_grant_token: ""
    endpoint: <s3-compatible-api-endpoint>
    bucket_name: <s3-bucket-name>
    dfs_link_resolver: <optional-dfs-link-resolver-url>
  storj:
    enabled: true
    access_key: <access-key>
    secret_key: <access-secret-key>
    bucket_name: <s3-bucket-name>
    link_share_service: https://link.storjshare.io
    endpoint: https://gateway.storjshare.io
    dfs_link_resolver: https://gateway.storjshare.io
database:
  kind: postgres
  host: 0.0.0.0
  port: 5432
  username: postgres
  password: Qwerty@123
  name: open_registry
