pipeline:
  inputs:
    - name: http
      host: 0.0.0.0
      port: 9880
  outputs:
    - name: stdout
      match: '*'
    - name: loki
      match: '*'
      line_format: json
      host: logs-prod-us-central1.grafana.net
      http_user: <grafana-cloud-user-id>
      http_passwd: <grafana-cloud-password/token>
